[package]
name        = "bs-mint-hooks"
authors     = [
  "Shane Vitarana <s@noreply.publicawesome.com>",
  "A Hardnett <hard-nett@users.noreply.github.com>"
]
description = "Mint hooks to allow extending minting contracts"
version     = { workspace = true }
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

[dependencies]
cosmwasm-schema      = { workspace = true }
cosmwasm-std         = { workspace = true }
cw-storage-plus      = { workspace = true }
schemars             = { workspace = true }
serde                = { workspace = true }
bs-controllers       = { workspace = true }
bs-std               = { workspace = true }
thiserror            = { workspace = true }
bs-mint-hooks-derive = { path = "./derive", version = "0.1.0" }
